<?php

declare(strict_types=1);

return [
    'dio accecato',
    'dio affogato nella merda',
    'dio aguzzino',
    'dio ammuffito',
    'dio appassito',
    'dio appestato',
    'dio asino',
    'dio asociale',
    'dio assassino',
    'dio assatanato',
    'dio ateo',
    'dio avvelenato',
    'dio bastardo',
    'dio bastonato',
    'dio becchino',
    'dio bestia',
    'dio boia',
    'dio brufoloso',
    'dio buffone',
    'dio cagnaccio',
    'dio camperista balsamico',
    'dio cancheroso',
    'dio cancro',
    'dio cane',
    'dio cane bastardo',
    'dio cannibale',
    'dio castrato',
    'dio checca',
    'dio ciclista senza sellino',
    'dio cleziano',
    'dio contrabbandiere',
    'dio cornuto',
    'dio corrosivo',
    'dio ebreo',
    'dio ecclesiastico',
    'dio evasore fiscale',
    'dio fagiano',
    'dio falsario',
    'dio falso',
    'dio fracico',
    'dio frocione',
    'dio fuoribordo',
    'dio furioso',
    'dio gobbo',
    'dio guerrafondaio',
    'dio impestato',
    'dio improbo',
    'dio inculato',
    'dio kamikaze',
    'dio ladro',
    'dio lebbroso',
    'dio lupo',
    'dio lurido',
    'dio mafioso',
    'dio maiale',
    'dio monco',
    'dio morto de fame',
    'dio omertoso',
    'dio pagliaccio',
    'dio papa',
    'dio pennellone',
    'dio pezzente',
    'dio piegato dalla fica',
    'dio pompinaro',
    'dio porco',
    'dio poser',
    'dio povero',
    'dio puttaniere',
    'dio rospo',
    'dio schifoso càn',
    'dio serpente',
    'dio spacciatore',
    'dio sporco',
    'dio squallido',
    'dio squalo',
    'dio stronzo',
    'dio sudicio',
    'dio suino',
    'dio superdotato come si gira si incula',
    'dio tamarro',
    'dio terrorista',
    'dio truffatore',
    'dio truzzo',
    'dio vaffanculo',
    'dio verginello',
    'dio zerbino',
    'diomerda',
    'porco dio',
    'porno dio',
    'dio merda',
    'diocane',
    'diomerda',
    'madonna assassina',
    'madonna bandita',
    'madonna bastarda',
    'madonna battona',
    'madonna bocchinara',
    'madonna capra',
    'madonna cornuta',
    'madonna cretina',
    'madonna crocifissa',
    'madonna diavola',
    'madonna fracica',
    'madonna fricchettona',
    'madonna ladra',
    'madonna indiavolata',
    'madonna lardona',
    'madonna lebbrosa',
    'madonna lurida',
    'madonna maiala',
    'madonna maledetta',
    'madonna mignotta',
    'madonna nana',
    'madonna pompinara',
    'madonna putrida',
    'madonna putrida vacca',
    'madonna puttana',
    'madonna scoreggiona',
    'madonna scrofa in calore',
    'madonna sorca',
    'madonna strozzina',
    'madonna stuprata',
    'madonna succhiacazzi',
    'madonna suina',
    'madonna trivellata',
    'madonna troia',
    'madonna vigliacca',
    'madonna zoccola',
    'madonna zoccola da gara',
    'mannaggia la madonna',
    'porca madonna',
    'puttana madonna',
    'puttana la madonna',
    'madonna discord',
    'dio frocio',
    'dio cappuccio',
    'dioaccecato',
    'dioaffogatonellamerda',
    'dioaguzzino',
    'dioammuffito',
    'dioappassito',
    'dioappestato',
    'dioasino',
    'dioasociale',
    'dioassassino',
    'dioassatanato',
    'dioateo',
    'dioavvelenato',
    'diobastardo',
    'diobastonato',
    'diobecchino',
    'diobestia',
    'dioboia',
    'diobrufoloso',
    'diobuffone',
    'diocagnaccio',
    'diocamperistabalsamico',
    'diocancheroso',
    'diocancro',
    'diocannibale',
    'diocastrato',
    'diochecca',
    'diociclistasenzasellino',
    'diocleziano',
    'diocontrabbandiere',
    'diocornuto',
    'diocorrosivo',
    'dioebreo',
    'dioecclesiastico',
    'dioevasorefiscale',
    'diofagiano',
    'diofalsario',
    'diofalso',
    'diofracico',
    'diofrocione',
    'diofuoribordo',
    'diofurioso',
    'diogobbo',
    'dioguerrafondaio',
    'dioimpestato',
    'dioimprobo',
    'dioinculato',
    'diokamikaze',
    'dioladro',
    'diolebbroso',
    'diolupo',
    'diolurido',
    'diomafioso',
    'diomaiale',
    'diomonco',
    'diomortodefame',
    'dioomertoso',
    'diopagliaccio',
    'diopapa',
    'diopennellone',
    'diopezzente',
    'diopiegatodallafica',
    'diopompinaro',
    'dioporco',
    'dioposer',
    'diopovero',
    'dioputtaniere',
    'diorospo',
    'dioschifosocàn',
    'dioserpente',
    'diospacciatore',
    'diosporco',
    'diosquallido',
    'diosqualo',
    'diostronzo',
    'diosudicio',
    'diosuino',
    'diosuperdotatocomesigirasiincula',
    'diotamarro',
    'dioterrorista',
    'diotruffatore',
    'diotruzzo',
    'diovaffanculo',
    'dioverginello',
    'diozerbino',
    'diomerda',
    'porcodio',
    'pornodio',
    'diomerda',
    'diomerda',
    'diomorto',
    'madonnaassassina',
    'madonnabandita',
    'madonnabastarda',
    'madonnabattona',
    'madonnabocchinara',
    'madonnacapra',
    'madonnacornuta',
    'madonnacretina',
    'madonnacrocifissa',
    'madonnadiavola',
    'madonnafracica',
    'madonnafricchettona',
    'madonnaladra',
    'madonnaindiavolata',
    'madonnalardona',
    'madonnalebbrosa',
    'madonnalurida',
    'madonnamaiala',
    'madonnamaledetta',
    'madonnamignotta',
    'madonnanana',
    'madonnapompinara',
    'madonnaputrida',
    'madonnaputridavacca',
    'madonnaputtana',
    'madonnascoreggiona',
    'madonnascrofaincalore',
    'madonnasorca',
    'madonnastrozzina',
    'madonnastuprata',
    'madonnasucchiacazzi',
    'madonnasuina',
    'madonnatrivellata',
    'madonnatroia',
    'madonnavigliacca',
    'madonnazoccola',
    'madonnazoccoladagara',
    'mannaggialamadonna',
    'porcamadonna',
    'puttanamadonna',
    'puttanalamadonna',
    'madonnadiscord',
    'diofrocio',
    'diocappuccio',
    'porcoddio',
    'dio can', // Veneto's version
    'stronzo',
    'stupido',
    'cazzo',
    'stocazzo',
    'vaffanculo',
];
