<?php

declare(strict_types=1);

return [
    // General insults
    'eikel',
    'hufter',
    'idioot',
    'mongool',
    'debiel',
    'sukkel',
    'klootzak',
    'klote',
    'lul',
    'lulletje',
    'trut',
    'zeikerd',
    'pannenkoek',

    // Stronger insults
    'teringlijer',
    'tyfuslijer',
    'kankerlijer',
    'teringhoer',
    'tyfuswijf',
    'kankerhoer',
    'kankeridioot',
    'kankermongool',
    'teringmongool',
    'pleurislijer',
    'kutwijf',
    'kutkind',
    'kutjong',
    'kutlul',
    'hoerenzoon',
    'hoerenjong',

    // Sexual insults
    'neuk',
    'neuken',
    'neuker',
    'kontneuker',
    'ballenlikker',
    'reetlikker',
    'anuslikker',
    'reetkever',
    'anushoofd',
    'kuthoofd',
    'aapneuker',

    // Profanities with numbers
    'k4nk3r',
    't3ring',
    'h0er',
    'l!j3r',
    'k¥t',
    'f*k',
    'm0ng00l',
    't¥fus',
    'h**r',
    'd3bi3l',

    // Common expletives
    'godverdomme',
    'verdomme',
    'gvd',
    'kak',
    'zeik',
    'shit',
    'fuck',

    // Racist and offensive terms (for filtering purposes)
    'nikker',
    'neger',
    'negerhoer',
    'jodenhoer',
    'kankerneger',
    'teringjood',
    'flikker',
    'mietje',

    // Compound insults
    'kankertokkie',
    'teringdebiel',
    'tyfusmongool',
    'kankerflikker',
    'klotetreiter',
    'zeikstraal',
    'teringvent',
    'hoerenvent',
    'kutvent',

    // Mild & funny insults
    'labbekak',
    'zakkewasser',
    'viespeuk',
    'drol',
    'kakkenest',
    'zuiplap',
    'kletskop',
    'blaaskaak',
    'droplul',

    // Variations with spaces
    'tering lijer',
    'kanker mongool',
    'tyfus hoer',
    'kut kind',
    'kloot zak',
    'neuk mij',
    'hoer zoon',
    'kanker wijf',
    'kanker tering',
    'zeik straal',
    'pleuris idioot',
    'mongool debiel',
    'tering lul',
    'god verdomme',
    'fuck jou',
    'shit hoofd',

    // Alternative spellings & disguised words
    'h0erenk!nd',
    'n3uk',
    'f*ck',
    'g0dverdomme',
    'tr!ngl!jr',
    'k4nker',
    'l¥l',
    'sh1t',
    'f@ck',
    'h0r3n',
    'gvdhoer',

    // English words often used in Dutch insults
    'motherfucker',
    'dumbass',
    'bitch',
    'asshole',
    'pussy',
    'slut',
    'retard',
    'wanker',
    'prick',

    // Extreme and creative Dutch insults
    'strontvlieg',
    'lulhannes',
    'zeiksnor',
    'achterlijke aap',
    'debiele pannenkoek',
    'teringpapzak',
    'grafzeiker',
    'dikke varken',
    'klotenboer',
    'klotezak',
    'teringneuker',
];
