<?php

declare(strict_types=1);

return [
    'cu',
    'cuzão',
    'fdp',
    'filho da puta',
    'caralho',
    'porra',
    'bosta',
    'merda',
    'pqp',
    'vai tomar no cu',
    'babaca',
    'otário',
    'imbecil',
    'pau no cu',
    'puta',
    'putaria',
    'safado',
    'vagabunda',
    'vagabundo',
    'viado',
    'boiola',
    'bicha',
    'desgraçado',
    'desgraçada',
    'arrombado',
    'escroto',
    'corno',
    'puta que pariu',
    'chupa rola',
    'vai se fuder',
    'vai se ferrar',
    'rola',
    'pau',
    'pinto',
    'buceta',
    'xota',
    'chupa cu',
    'fodido',
    'foda-se',
    'caralhudo',
    'pau no rabo',
    'cu de burro',
    'piranha',
    'cretino',
    'trouxa',
    'burro',
    'viado de merda',
    'escória',
    'nojentinho',
    'fedido',
    'putaça',
    'paneleiro',
    'broxa',
    'mocorongo',
    'vagaba',
    'nojento',
    'tarado',
    'cabeça de pica',
    'cabecinha',
    'mijão',
    'cagão',
    'fedorento',
    'lixo',
    'crápula',
    'chifrudo',
    'besta quadrada',
    'chupa pinto',
    'chupa pica',
    'bucetuda',
    'brioco',
    'mongo',
    'mongoloide',
    'mongol',
];
