<?php

declare(strict_types=1);

return [
    'arrombado',
    'babaca',
    'besta quadrada',
    'bicha',
    'boiola',
    'bosta',
    'brioco',
    'broxa',
    'buceta',
    'bucetuda',
    'burro',
    'cabecinha',
    'cabeça de pica',
    'cagão',
    'caralho',
    'caralhudo',
    'chifrudo',
    'chupa cu',
    'chupa pica',
    'chupa pinto',
    'chupa rola',
    'corno',
    'cretino',
    'crápula',
    'cu',
    'cu de burro',
    'cuzão',
    'desgraçada',
    'desgraçado',
    'escroto',
    'escória',
    'fdp',
    'fedido',
    'fedorento',
    'filho da puta',
    'foda-se',
    'fodido',
    'imbecil',
    'lixo',
    'merda',
    'mijão',
    'mocorongo',
    'mongo',
    'mongol',
    'mongoloide',
    'nojentinho',
    'nojento',
    'otário',
    'paneleiro',
    'pau',
    'pau no cu',
    'pau no rabo',
    'pinto',
    'piranha',
    'porra',
    'pqp',
    'puta',
    'puta que pariu',
    'putaria',
    'putaça',
    'rola',
    'safado',
    'tarado',
    'trouxa',
    'vagaba',
    'vagabunda',
    'vagabundo',
    'vai se ferrar',
    'vai se fuder',
    'vai tomar no cu',
    'viado',
    'viado de merda',
    'xota',
];
